### ISSUE TITLE
unable to allocate file descriptor table

### ISSUE THREAD

**Issue by ander1044** [srlabs/SIMTester#5]
Getting unable to allocate file descriptor table - out of memory. I'm currently running it on 4GB RAM and it previously worked without any issues.

**Comment by tatulea** [comment]
Hey @ander1044, can you give me more details about your setup? What Java version are you using?

**Comment by ander1044** [comment]
@tatulea  I have moved to an 8GB pc now running Kali 2024.3 and Java 1.8.0_221 and still getting the same memory error

**Comment by ander1044** [comment]
@tatulea I have managed to fix the error by completely uninstalling Java and reinstalling it again, I'm guessing the issue is with Java 1.8.0_*.
